import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "@/components/providers";
import localFont from "next/font/local";

const sfDisplay = localFont({
  src: "./fonts/SF-Pro-Display.otf",
  variable: "--font-heading",
  display: "swap",
});

const sfRounded = localFont({
  src: "./fonts/SF-Pro-Rounded.otf",
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${sfRounded.variable} ${sfDisplay.variable} font-sans bg-primary-50 text-quinary-950 transition-colors duration-300`}
      >
        <Providers>
          <Navbar />
          <main className="pt-20">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
